resources:
  - ../../base
patchesStrategicMerge:
- |-
  apiVersion: training.eduk8s.io/v1alpha2
  kind: Workshop
  metadata:
    name: cnd-deploy-practices
  spec:
    environment:
      objects:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: files
          namespace: $(workshop_namespace)
        spec:
          replicas: 1
          selector:
            matchLabels:
              deployment: files
          strategy:
            type: Recreate
          template:
            metadata:
              labels:
                deployment: files
            spec:
              containers:
              - name: nginx
                image: cnd-deploy-practices
                imagePullPolicy: IfNotPresent
                volumeMounts:
                  - mountPath: /usr/share/nginx/html
                    name: data
              volumes:
              - name: data
                emptyDir: {}

