resources:
- ../
patchesStrategicMerge:
- |-
  apiVersion: training.eduk8s.io/v1alpha2
  kind: Workshop
  metadata:
    name: cnd-deploy-practices
  spec:
    environment:
      objects:
      - kind: Deployment
        metadata:
          name: files
        spec:
          template:
            spec:
              containers:
              - name: nginx
                image: cnd-deploy-practices
                imagePullPolicy: IfNotPresent
                  volumeMounts:
                  - mountPath: /usr/share/nginx/html
                    name: data
                volumes:
                - name: data
                  emptyDir: {}